### ISSUE TITLE
Wrong method signatures

### ISSUE THREAD

**Issue by wo80** [m-reuter/arpackpp#1]
I think some of the method signatures for calling the SuperLU routines are wrong. Please take a look at my commit: https://github.com/wo80/arpackpp/commit/2635daa791b15aad5a6aa9209e6a28f35cc9068b

I'll create a pull request, if you confirm.

**Comment by m-reuter** [comment]
Hi. Looked at your recent update (for SuperLU 5.0) and it works nicely. I think we should update to that. Thanks
