### ISSUE TITLE
Wrong eigenvalues with UMFpack

### ISSUE THREAD

**Issue by manusethi** [m-reuter/arpackpp#10]
Hi,

I am using arpackpp to solve a generalized eigenvalue for symmetric sparse matrices. However, I noticed I get negative eigenvalues for a symmetric positive semi-definite matrix. When I replace the call with SuperLU instead of UMFpack then I get correct values. Any one noticed this problem?

I don't mind using SuperLU but I am calling my program within MPI. And I get memory mapping error and segfault when I use SuperLU within MPI. (I am using the serial SuperLU version as provided in the library. I just need to call it within in my MPI program which uses MPI just to divide the data into pieces. I am not using SuperLU-dist). If I don't use MPI, SuperLU works fine.

The UMFPack works within my MPI program without any segfault but gives negative eigenvalues.

 I would greatly appreciate any help.

Thanks,
Manu

**Comment by m-reuter** [comment]
I used both superLU and Umfpack before for sparse symmetric matrices and got basically the same results. I was not using MPI.  
You could test
- Umfpack without MPI on one of those matrices to see if it is the MPI
- Maybe try to compile the umfpack examples with MPI to see if that changes anything.

**Comment by manusethi** [comment]
Thanks! I have tried umfpack without MPI and still found the same problem of negative eigenvalues. I will try compiling umfpack examples with MPI also.

**Comment by m-reuter** [comment]
are the arpackpp umfpack examples working for you? There should be no negative eigenvalues. For example

./usymgshf 
ARumSymPencil::ExpandAsB(0) ... ( N = 100  NNZ = 298 ) done!
 symbolic status: 0
 numeric status: 0

Testing ARPACK++ class ARluSymGenEig 
Real symmetric generalized eigenvalue problem: A_x - lambda_B*x
Shift and invert mode

Dimension of the system            : 100
Number of 'requested' eigenvalues  : 4
Number of 'converged' eigenvalues  : 4
Number of Arnoldi vectors generated: 9
Number of iterations taken         : 6

Eigenvalues:
  lambda[1]: 9.8704
  lambda[2]: 39.4912
  lambda[3]: 88.8909
  lambda[4]: 158.117

||A_x(0) - lambda(0)_B_x(0)||: 6.52649e-14
||A_x(1) - lambda(1)_B_x(1)||: 1.60914e-14
||A_x(2) - lambda(2)_B_x(2)||: 8.59726e-15
||A_x(3) - lambda(3)_B_x(3)||: 9.8449e-15

**Comment by manusethi** [comment]
Thanks @m-reuter so much for your help. I will get back to you next week after testing ARPACK++ examples with MPI.

**Comment by m-reuter** [comment]
Has this been resolved?
You can also check if SuperLU without MPI also gives you negative eigenvalues, because maybe the matrix is incorrect (or not what you think it should be)?
