### ISSUE TITLE
compiling on windows

### ISSUE THREAD

**Issue by raphaelsulzer** [m-reuter/arpackpp#11]
Hi, 

Is there any way to compile arpackpp into a Windows DLL? My goal is to P/Invoke this in C#.

Cheers,
Raphael

**Comment by m-reuter** [comment]
Not that I know of. Also note that arpackpp is only headers (except for the examples).Am 28.07.2017 07:14 schrieb RaphaelS <notifications@github.com>:Hi,
Is there any way to compile arpackpp into a Windows DLL? My goal is to P/Invoke this in C#.
Cheers,
Raphael
