### ISSUE TITLE
Installing with dynamic gfortran library

### ISSUE THREAD

**Issue by pcarbo** [m-reuter/arpackpp#13]
It looks like `arpackpp` has not been terribly active recently but I am wondering if you would be able to address a small issue we have encountered trying to install `arpackpp` on our compute cluster at the University of Chicago. 

We use Scientific Linux 7. I have all the dependencies installed. However, the `cmake` step fails because it is unable to find a static gfortran library; on our system, we only have dynamic gfortran libraries installed:

```
$ ls -1 /lib64/libgfortran*
/lib64/libgfortran.so.1
/lib64/libgfortran.so.1.0.0
/lib64/libgfortran.so.3
/lib64/libgfortran.so.3.0.0
```

Indeed, there is a note in the `CMakeLists.txt` file that the static gfortran library is preferred. Is it possible to revise the cmake procedure to check for availability of `libgfortran.so` as well? Or is there a reason why this is discouraged? I think some Linux setups by default will not have the static libraries installed, and this will make it more difficult to install `arpackpp` on these systems.

**Comment by pcarbo** [comment]
This is the relevant output I get from running `cmake`:

```
-- gfortran is required but could not be found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GFORTRAN_LIB
```

**Comment by m-reuter** [comment]
it should work also with a so. The cmake looks for the static library first, but then simply searches for any libgfortran.  Anyway, this is just a header library and requires no compilation. Only the examples need the dependencies. So you could remove the block in the cmake file and just install ? or manually copy all .h files.

**Comment by pcarbo** [comment]
Thank you for the quick response @m-reuter. I should have read the README more carefully!

If I wanted to run the examples, could you clarify which block in the cmake file I would remove to allow for using the `.so` gfortran library?

**Comment by m-reuter** [comment]
Have you tried specifying the libgfortran.so with full path to the cmake var GFORTRAN_LIB ?

**Comment by m-reuter** [comment]
I have also changed some behaviour in the CMmake file with a more efficient search for the gfortran library, maybe that fixes it?

**Comment by pcarbo** [comment]
@m-reuter Thank you. It has been a while since I have looked at this but I've made a note to test the arpackpp installation with your fix—I'll try to get back to you soon.

**Comment by m-reuter** [comment]
Have you had a chance to test this? Otherwise I will close this issue for now.

**Comment by pcarbo** [comment]
Sorry! Yes, @m-reuter, please go ahead and close the issue.
