### ISSUE TITLE
Error with multiple threads

### ISSUE THREAD

**Issue by GGGRY** [m-reuter/arpackpp#17]
Hello, 
When i tried to solve several eigen value problems in prallel, i met an error:
```
Arpack error in Aupp.
-> Maximum number of iterations taken.
```
Basically, i used "for" loop with openMP for parallelizing in multiple threads.  I can't find any description about whether arpackpp is thread-safe or not.

All the best

**Comment by m-reuter** [comment]
Sadly it is not thread safe ( I think because arpack isn't ).

**Comment by GGGRY** [comment]
Thanks for your quick response. Well, i close this.

All the best
