### ISSUE TITLE
Question about the arpackpp

### ISSUE THREAD

**Issue by yao2019research** [m-reuter/arpackpp#21]
Dear Doctor Martin Reuter,

I am guobiao Yao and following your github for a period of time. Because I am doing my research on line feature matching by using the libraries of  arpackpp. So I need install the arpackpp in my computer with Window10 64bit. So is it feasible if I want intall the arpackpp in my compuer?
Thanks for your help.
Looking forward to your reply.
Guobiao Yao in OSU PCVLAB

**Comment by m-reuter** [comment]
Hi Guobiao

I haven't tried in on Windows, but it should work. It is a header-library, so it compiles together with your program when you include the headers. Only the programs under examples are compiled, but that is not necessary.
