### ISSUE TITLE
Is it possible to use `gemv` from BLAS directly on `ARdsNonSymMatrix`?

### ISSUE THREAD

**Issue by dburov190** [m-reuter/arpackpp#23]
Hi, I wonder if it's possible to perform this operation:
```c++
w = alpha * matrix * v;
```
where `matrix` is of type `ARdsNonSymMatrix`, `v` and `w` are vectors, and `alpha` is a double?

There is `matrix.MultMv`, which does exactly that but without `alpha` multiplication. There's also a `gemv` function (it is used internally in `matrix.MultMv`) which could do that but the problem is `A` member is protected in the `ARdsNonSymMatrix` class.

Thank you!

**Comment by m-reuter** [comment]
Not sure. Maybe you can do M * ( a*v) ?

**Comment by dburov190** [comment]
That's what I ended up using. Thank you! Closing then.
