### ISSUE TITLE
Generalised eigenvalue problem with shift-inverse mode using UMFPACK

### ISSUE THREAD

**Issue by ArturGesla** [m-reuter/arpackpp#25]
Hello

Thank you for keeping the repository up - I profit a lot from the code available here.

When trying to solve generalized eigenvalue problem with shift-inverse mode I saw that the example using UMFPACK:

/arpackpp/examples/umfpack/nonsym/unsymgsc.cc

does not compile. In fact it is commented out in the CMakeLists.txt. However the coresponding SuperLU file:

/arpackpp/examples/superlu/nonsym/lnsymgsc.cc

is compiled and the example works. Is the umfpack not meant to be used for this kind of problem or was is just not implemented yet?

Yours
Artur

**Comment by m-reuter** [comment]
Hi Artur, 
I never used the non-sym code much, not sure why this has been left out, nor why it fails to compile. I think when UMFPACK moved to SuiteSparse, we only updated the sym examples (because those were the ones we used) and left the non-sym for later.

**Comment by ArturGesla** [comment]
Ok, I see. Thank you for the response. Have a nice day :)
