### ISSUE TITLE
Plans to make a release?

### ISSUE THREAD

**Issue by yurivict** [m-reuter/arpackpp#26]
The last release was in 2015. Then  there were many commits in 2019.

Maybe it makes sense to make a release?

**Comment by m-reuter** [comment]
Those newer commits were mainly related to external libraries, installation and building (cmake, travis). Very little changes to the library. But I also agree, that we should make a new release at some point soon. Probably good after the current ongoing updates to the cmake and CI system.

**Comment by m-reuter** [comment]
published 2.4.0 with our awesome new cmake system, bumped dependencies and fixes.
