### ISSUE TITLE
Update the ARPACK++ documentation

### ISSUE THREAD

**Issue by wo80** [m-reuter/arpackpp#3]
I have created a GitHub project for the ARPACK++ documentation: https://github.com/wo80/arpackpp-doc

There's a todo list in the projects' readme. Maybe you find some time and have a look.
Anyways, feel free to add the pdf to this repository.

**Comment by m-reuter** [comment]
This is great! I think we should replace the existing doc with this. I wonder if it makes sense to merge  these projects or keep them separate and only add the PDF? Having it in one place will increase the chance that others will contribute to the doc also. What do you think?

**Comment by wo80** [comment]
I was thinking about that too. Having a seperate repository obviously results in a cleaner Git history and a cleaner way of handling issues. But since this is a rather small project, that might not be crucial.

**Comment by m-reuter** [comment]
Let's keep it separate for now. Once it replaces the existing doc files, we can always merge it into this project, e.g. as a subfolder of doc. And use it to generate the doc/pdf file (via make doc or something). Also, I updated the INSTALL and README, and some of that information (cmake etc) may be useful for the manual.
