### ISSUE TITLE
Duplicate symbols when linking two objects including arsnsym.h

### ISSUE THREAD

**Issue by atantet** [m-reuter/arpackpp#5]
Hello,
When linking two different objects both including some arpackpp headers, I get symbol duplicate errors (see below). It seems that some global variables or members are declared in these headers without the "extern" keyword. This is problematic when the user is designing a library on top of arpackpp with implementations in different files than the headers. Or am I getting confused somewhere?

`g++ -undefined dynamic_lookup -o spectrum.out spectrum.o ../cfg/readConfig.o -L/Users/atantet/PhD/dev/lib/ -lgsl -lconfig++ -lergopack

duplicate symbol ArpackError::Set(ArpackError::ErrorCode, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in:
    spectrum.o
    /Users/atantet/PhD/dev/lib//libergopack.a(transferSpectrum.o)

duplicate symbol ArpackError::code       in:
    spectrum.o
    /Users/atantet/PhD/dev/lib//libergopack.a(transferSpectrum.o)

duplicate symbol MemoryOverflow()     in:
    spectrum.o
    /Users/atantet/PhD/dev/lib//libergopack.a(transferSpectrum.o)

duplicate symbol _debug_ in:
    spectrum.o
    /Users/atantet/PhD/dev/lib//libergopack.a(transferSpectrum.o)

ld: 4 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
make: **\* [spectrum.out] Error 1
`

**Comment by m-reuter** [comment]
checkout b0266311dc16641b774a69d49e6c66dc5ef6bbf2 to see if that fixes the problem (I had to add a few inlines, extern and a special template workaround to initialize a static member)

**Comment by atantet** [comment]
The fix works perfectly! Thanks for the very fast reaction and for maintaining this great software!
