### ISSUE TITLE
superlu 5.0 should set $BLAS

### ISSUE THREAD

**Issue by dingxiong** [m-reuter/arpackpp#7]
"install-superlu.sh" says that if $BLAS is not equal to "SYSTEM", then it will resort to locally installed openblas. For people who have done `apt-get install libopenblas-dev`, maybe it is better to make it clear:
`$export BLAS=SYSTEM && ./install-superlu.sh`

**Comment by m-reuter** [comment]
What exactly do you mean? Where should this change be made? Thanks.
