### ISSUE TITLE
Posible memory leak?

### ISSUE THREAD

**Issue by WaVEV** [m-reuter/arpackpp#9]
Hi
When I compute eigenvalues with ARluSymGenEig a few times, the memory required is only increase. 

In this [program](https://github.com/WaVEV/Tesis/blob/master/pozo-2.cc) 
I call that function with diferent values of hsim_val, ms_val, mv_val. (the irow is equal in these 3 matrix)
I call it 10 times, and the required memory in every call increase the total memory required ( and when the matrix is big, requires 1.5 GB in each call)

``` C++
void eigen(int n, int nz, std::vector<double> &exp_val, std::vector<double> &evec){
  ARumSymMatrix<double> A(n, nz, hsim_val, irow, pcol, 'U');
  ARumSymMatrix<double> B(n, nz, ms_val, irow, pcol, 'U');
  ARumSymMatrix<double> C(n, nz, mv_val, irow, pcol, 'U');
  ARluSymGenEig<double> dprob('C', NEV, A, B, -10, "SA");

  dprob.FindEigenvectors();
  evec.resize(NEV);
  double *Ax = new double[n * NEV];
  for (int i=0; i<NEV; i++) {
    evec[i] = dprob.Eigenvalue(i);
    C.MultMv(dprob.RawEigenvector(i), &Ax[n * i]);
  }
  double *Rx = new double[NEV];
  for(int i=0 ; i<NEV ; i++){
      Rx[i] = 0;
      for(int o=0 ; o<n ; o++){
        Rx[i] +=  dprob.RawEigenvector(i)[o] * Ax[o + n * i];
      }
  }

  delete[] Ax;
  exp_val.resize(NEV);
  for(int i=0 ; i<NEV ; i++){
    exp_val[i] = Rx[i];
  }
  delete[] Rx;
}
```

**Comment by m-reuter** [comment]
To make sure it is not in your code, maybe try looping over the code in lsymgcay (superlu example dir) several times and see if memory increases also. I can take a look if you find a simple test example that shows this behavior.
Thanks

**Comment by WaVEV** [comment]
Thanks for reply. I ll try today

**Comment by WaVEV** [comment]
The program lsymgcay ends with Segmentation fault (core dumped) :(. When call  ARluSymGenEig

**Comment by m-reuter** [comment]
It is working on our systems, so I think that something is wrong with your installation. Maybe the SuperLU got compiled with a different BLAS than the arpackpp example? You should try recompiling SuperLU with the same BLAS. Maybe you also need to re-install / re-compile other libraries (ARPACK). What system are you on?

**Comment by WaVEV** [comment]
Linux 4.4.0-45-generic #66~14.04.1-Ubuntu. 
I compiled the code with cmake and make.

But I forget change some directories and machine-dependent directives contained into this file prior to compiling the examples. I ll try again with change something in Makefile.ini.

**Comment by m-reuter** [comment]
Any more thoughts on this issue, before I close it?

**Comment by WaVEV** [comment]
Sorry, I forget this, Yes it is working well now, The problem was  BLAS.
Thank you so much for your help.
